spring:
  application:
    name: config-server
  cloud:
    config:
      label: develop_study
      name:
      server:
        git:
          #uri: https://github.com/forezp/SpringcloudConfig/
          searchPaths: respo
          username:
          password:
          uri: https://github.com/HelloWorld324234/springcloud-demo/
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/

