eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

server:
  port: 8763

spring:
  application:
    name: service-ribbon

ribbon:
  eureka:
    enabled: true
